// core-frontend/src/app/katalog/page.tsx
import { getCategories, getPage } from '@/shared/api'
import styles from './styles.module.scss'
import Link from 'next/link'
import { TABS } from './constants'

const PAGE = 'katalog'

export async function generateMetadata() {
  const page = await getPage(PAGE)

  return {
    title: page?.seo_title ?? 'Каталог',
    description: page?.seo_description ?? '',
    keywords: page?.seo_keywords ?? '',
  }
}

export default async function Katalog() {
  const categories = await getCategories()

  if (!categories?.length) {
    return (
      <section>
        <h2>Категорий нет</h2>
      </section>
    )
  }

  const categoriesList = (parentId: number | null = null) => {
    return (
      categories
        .filter((c) => c.parent_id === parentId && !!c.active)
        .sort((a, b) => (a.position < b.position ? -1 : 1)) || {}
    )
  }

  return (
    <>
      <div className={styles.list}>
        {categoriesList().map(({ id: parent_id, name, url }) => (
          <article key={parent_id}>
            <Link href={`/menu/${url}`}>
              <span className={styles.elemTitle}>{name}</span>
            </Link>

            <ul className={styles.details}>
              {categoriesList(parent_id).map(({ id, name, url }) => (
                <Link href={`/menu/${url}`} key={id}>
                  <span>{name}</span>
                </Link>
              ))}
            </ul>
          </article>
        ))}
      </div>

      <section className={styles.tabs}>
        <hr />

        {TABS.map((tab) => (
          <div key={tab.url} className={styles.tab}>
            <Link href={tab.url} className={styles.tabLink}>
              {tab.title}
            </Link>

            {tab.tabs?.length && (
              <div className={styles.tabDetails}>
                {tab.tabs.map((tab) => (
                  <div key={tab.url} className={styles.subTab}>
                    <Link href={tab.url} className={styles.subTabLink}>
                      {tab.title}
                    </Link>
                  </div>
                ))}
              </div>
            )}
          </div>
        ))}
      </section>
    </>
  )
}

// frontend/pages/katalog/index.vue
<template>
  <section class="v-categories-list">
    <div
      v-for="{ id: parent_id, name, url } in categoriesList()"
      :key="parent_id"
    >
      <nuxt-link :to="`/menu/${url}`">
        <span class="v-categories-list__elem-title">{{ name }}</span>
      </nuxt-link>

      <ul class="v-categories-list__details mt-4">
        <li v-for="{ id, name, url } in categoriesList(parent_id)" :key="id">
          <nuxt-link :to="`/menu/${url}`">
            <span>{{ name }}</span>
          </nuxt-link>
        </li>
      </ul>
    </div>
  </section>
</template>

<script>
import { mapGetters } from "vuex";

export default {
  head() {
    return {
      title: this.page?.seo_title || "Каталог",
      meta: [
        {
          hid: "description",
          name: "description",
          content: this.page?.seo_description || "",
        },
        {
          hid: "keywords",
          name: "keywords",
          content: this.page?.seo_keywords || "",
        },
      ],
    };
  },
  data: () => ({
    categoryDetail: null,
    categoryDetailSecond: null,
  }),
  computed: {
    ...mapGetters("app", ["page", "categories"]),
    categoriesList() {
      return (parentId = null) =>
        this.categories
          .filter((c) => c.parent_id === parentId && !!c.active)
          .sort((a, b) => (a.position < b.position ? -1 : 1)) || {};
    },
  },
  async fetch({ store }) {
    const appVariables = store.getters.appVariables;
    const categories = store.getters.categories;
    if (!appVariables || !appVariables.length) {
      await store.dispatch("app/fetchVariables");
    }
    if (!categories || !categories.length) {
      await store.dispatch("app/fetchCategories");
    }
    await store.dispatch("app/fetchPage", "katalog");
  },
};
</script>

<style lang="scss">
@import "@/assets/mixins.scss";

.v-categories-list {
  display: grid;
  grid-template-columns: 1fr;
  gap: 30px;
  padding: 10px;
  font-size: 14px;
  padding: 20px 20px;

  ul {
    padding: 0;
  }

  li {
    list-style: none;
  }

  a {
    text-decoration: none;
    color: #000;
  }

  &__elem-title {
    font-size: 22px;
    color: $colorSecondary;

    &:hover {
      text-decoration: underline;
    }
  }

  &__details {
    display: flex;
    flex-direction: column;
    gap: 4px;
    margin: 0 auto;

    & span {
      &:hover {
        text-decoration: underline;
      }
    }
  }

  @include tablet {
    grid-template-columns: 1fr 1fr;
    padding: 40px 60px;
  }

  @include laptop {
    max-width: 1200px;
    width: 100%;
    margin: 0 auto;
    grid-template-columns: 1fr 1fr 1fr;
  }
}
</style>
